[telegram]
token = "5831008872:AAGj794ZQiE8csKTZd3FZZxBjWau8InPoXc"
workers = 1
admins = [5166575484]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 0
api_hash = ""

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = ""
